version: "3.9"

services:
  odoo:
    image: odoo:18.0
    container_name: mirapana_odoo
    depends_on:
      - db
    # No es necesario exponer el puerto 8069 aquí si usas Traefik
    # ports:
    #  - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=qwerty76%&/
      - PROXY_MODE=True
      - WEB_BASE_URL=https://xservice.store
    volumes:
      - odoo_data:/var/lib/odoo
    labels:
      # Habilita Traefik para este contenedor
      - "traefik.enable=true"
      # --- Regla para HTTP (redirección) ---
      - "traefik.http.routers.odoo-http.entrypoints=web"
      - "traefik.http.routers.odoo-http.rule=Host(`xservice.store`)"
      - "traefik.http.routers.odoo-http.middlewares=https-redirect"
      # --- Regla para HTTPS ---
      - "traefik.http.routers.odoo-https.entrypoints=websecure"
      - "traefik.http.routers.odoo-https.rule=Host(`xservice.store`)"
      - "traefik.http.routers.odoo-https.tls.certresolver=letsencrypt"
      # --- Servicio que apunta a Odoo ---
      - "traefik.http.services.odoo-service.loadbalancer.server.port=8069"
    networks:
      - net_service
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: odoo_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=qwerty76%&/
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net_service
      
volumes:
  db_data:
  odoo_data:

networks:
  net_service:
    external: true